backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "log"
    label: "Log"
    folder: "src/pages/log"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Category", name: "category", widget: "hidden", default: "Log"}

  - name: "code"
    label: "Code"
    folder: "src/pages/code"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Category", name: "category", widget: "hidden", default: "Code"}
  
  - name: "design"
    label: "Design"
    folder: "src/pages/design"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Category", name: "category", widget: "hidden", default: "Design"}

  - name: "lab"
    label: "Lab"
    folder: "src/pages/lab"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Category", name: "category", widget: "hidden", default: "Lab"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "About-about", name: "aboutAbout", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Q&A", name: "qna", widget: "list", fields: [
                {label: "Question", name: "question", widget: "string"},
                {label: "Answer", name: "answer", widget: "string"}
              ]}
            ]}
          - {label: "About-resume", name: "aboutResume", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Name", name: "name", widget: "string", default: "Will Kim"}
              {label: "Experience", name: "experience", widget: "list", fields: [
                {label: "Company", name: "company", widget: "string"},
                {label: "Position", name: "position", widget: "string"},
                {label: "Start Date", name: "startDate", widget: "date", format: "MMM YYYY"},
                {label: "Currently Working", name: "currentlyWorking", widget: "boolean", default: true},
                {label: "End Date", name: "endDate", widget: "date", format: "MMM YYYY"},
                {label: "Location", name: "location", widget: "string"},
                {label: "Description", name: "description", widget: "text"}
            ]},
              {label: "Volunteer", name: "volunteer", widget: "list", fields: [
                {label: "Organization", name: "position", widget: "string"},
                {label: "Position", name: "position", widget: "string"},
                {label: "Start Date", name: "startDate", widget: "date", format: "MMM YYYY"},
                {label: "Currently Working", name: "currentlyWorking", widget: "boolean", default: true},
                {label: "End Date", name: "endDate", widget: "date", format: "MMM YYYY"},
                {label: "Location", name: "location", widget: "string"},
                {label: "Description", name: "description", widget: "text"}
            ]},
              {label: "Education", name: "education", widget: "list", fields: [
                {label: "School", name: "school", widget: "string"},
                {label: "Start Date", name: "startDate", widget: "date", format: "YYYY"},
                {label: "Currently Attending", name: "currentlyAttending", widget: "boolean", default: true},
                {label: "End Date", name: "endDate", widget: "date", format: "YYYY"},
                {label: "Degree", name: "degree", widget: "string"},
                {label: "Major", name: "major", widget: "string"}
            ]},
              {label: "Award", name: "award", widget: "list", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Date", name: "date", widget: "date", format: "MMM YYYY"},
                {label: "Description", name: "description", widget: "text"}
            ]}
          ]}
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Callout", name: "callout", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}